
version: '3.7'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    networks:
      Recommender:
        aliases:
          - frontend.recommender
    depends_on:
      - backend

    volumes:
      - ./frontend:/app

    restart: always

  backend:
    build: backend
    ports:
      - 5000:5000
    networks:
      Recommender:
        aliases:
          - api.backend

    volumes:
      - ./backend:/app

    restart: always

networks:
  Recommender: #external: true use if you ran docker network create Transcription